### ISSUE TITLE
Composer autoload is not wotking

### ISSUE THREAD

**Issue by regonzalom** [shuchkin/simplexlsxgen#49]
I am using a framework called cakephp. The installation for composer completed successfully, but the SimpleXLSXGen class does not load automatically. I am attaching my composer.json file
[composer.json.txt](https://github.com/shuchkin/simplexlsxgen/files/7712591/composer.json.txt)
.

**Comment by shuchkin** [comment]
Re: [shuchkin/simplexlsxgen] Composer autoload is not wotking (Issue #49)



Hello, Gonzalo.

there conflict

please remove line 40
    "classmap": ["vendor/shuchkin/simplexlsxgen/src"]







I am using a framework called cakephp. The installation for composer completed successfully, but the SimpleXLSXGen class does not load automatically. I am attaching my composer.json file
composer.json.txt
.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 





--
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by regonzalom** [comment]
Hi Sergey,

Thanks for your time. I affair I have same mistake (after remove the line)...

![image](https://user-images.githubusercontent.com/1321510/146253967-91271f60-2658-48b1-81f4-91a122b5b298.png)

I attach mi file in current state.

[composer.json.txt](https://github.com/shuchkin/simplexlsxgen/files/7722225/composer.json.txt)

Thanks again,
Gonzalo

**Comment by shuchkin** [comment]
Re: [shuchkin/simplexlsxgen] Composer autoload is not wotking (Issue #49)



Gonzalo,

you have to figure out your autoloading problems yourself

anytime u can use
require_once "path/to/SimpleXLSXGen.php";








Hi Sergey,
Thanks for your time. I affair I have same mistake (after remove the line)...
I attach mi file in current state.
composer.json.txt
Thanks again,
Gonzalo
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 





--
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin
