### ISSUE TITLE
wrong autowidth of first column under row with merged columns

### ISSUE THREAD

**Issue by setro-ru** [shuchkin/simplexlsxgen#92]
Добрый день, Сергей.

Извините, пишу по-русски, на английском больше запутаю )

Не знаю, баг это или нет, но ситуация следующая:

Первую строку делаю всего с 1 значением массива - заголовок таблицы, соответственно в этой строке объединяю n-е количество столбцов (сколько нужно, к примеру 10 колонок)

Следующая строка - это названия столбцов со включенным autoFilter (не знаю важно это или нет, но думаю, что нет)
Далее строки - соответственно значения.

На выходе получаю первый столбец той ширины, которой равна длине заголовка, хотя заголовок находится в первой строке с объединенными ячейками. Как будто я не объединял ячейки в первой строке. Получается, при объединении ячеек автоширина для столбца работает так, как будто эта ячейка не объединялась с другими.

Не знаю смог ли объяснить, на скринах думаю понятнее будет. Скрин без объединения ячеек и с объединением.

Очень неудобно, особенно если заголовок длинный (

За проект спасибо, очень выручили.
![nonmerged](https://user-images.githubusercontent.com/122192224/212646470-20883ab3-95b6-4331-bf3b-5c651cdea55b.jpg)
![merged](https://user-images.githubusercontent.com/122192224/212646465-de4c2de5-ba6c-45a2-b4f6-87b300e2a512.jpg)

**Comment by shuchkin** [comment]
Re: [shuchkin/simplexlsxgen] wrong width of foirst column under row with merged columns (Issue #92)



Привет,

setColWidth сбрасывает автоширину
нумерация колонок начинается с 1
ширина указывается в символах







Добрый день, Сергей.
Извините, пишу по-русски, на английском больше запутаю )
Не знаю, баг это или нет, но ситуация следующая:
Первую строку делаю всего с 1 значением массива - заголовок таблицы, соответственно в этой строке объединяю n-е количество столбцов (сколько нужно, к примеру 10 колонок)
Следующая строка - это названия столбцов со включенным autoFilter (не знаю важно это или нет, но думаю, что нет)
Далее строки - соответственно значения.
На выходе получаю первый столбец той ширины, которой равна длине заголовка, хотя заголовок находится в первой строке с объединенными ячейками. Как будто я не объединял ячейки в первой строке.
Установка ширины столбца setColWidth не помогает.
Не знаю смог ли объяснить, на скринах думаю понятнее будет. Скрин без объединения ячеек и с объединением.
Очень неудобно, особенно если заголовок длинный (
За проект спасибо, очень выручили.


—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>





--
Thank You
Sergey
http://www.sibvision.ru/
http://www.smspilot.ru/
https://twitter.com/shuchkin
https://www.facebook.com/shuchkin

**Comment by setro-ru** [comment]
да, это я уже экспериментировать стал с setColWidth, но его использовать не могу
у меня генерятся разные файлы с разной шириной первой колонки
а беда именно в том, что автоширина некорректно рассчитвыает ширину первой колонки, когда выше в строке объединенные ячейки идут, по идее в объединенных ячейках длина текстовой строки не должна влиять на ширину 1 колонки во всей книге

**Comment by shuchkin** [comment]
see code example here
https://github.com/shuchkin/simplexlsxgen/issues/88
